ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS duration_seconds INT DEFAULT 0;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS total_usage_seconds INT DEFAULT 0;